SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (
    SELECT DISTINCT PARENT_ITEM_ID
    FROM ITEM_TREE
    # NOT IN을 사용할 때, 리스트 안에 NULL이 포함되면 결과가 UNKNOWN으로 평가되어
    # 아무것도 반환되지 않거나 예상치 못한 결과가 나옴
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID DESC