SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE LEFT(I.SEX_UPON_INTAKE, 6) = 'Intact' AND (LEFT(O.SEX_UPON_OUTCOME, 6) = 'Spayed' OR LEFT(O.SEX_UPON_OUTCOME, 8) = 'Neutered')
ORDER BY I.ANIMAL_ID