SELECT ROUTE,
    # TOTAL_DISTANCE는 CONCAT() 함수로 인해 더 이상 숫자가 아닌 문자열
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
# 이러면 틀림
# ORDER BY TOTAL_DISTANCE DESC
ORDER BY SUM(D_BETWEEN_DIST) DESC