SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
) AS J ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER) + J.JULY_TOTAL DESC
LIMIT 3;

SELECT F.FLAVOR
FROM FIRST_HALF F
LEFT JOIN JULY J
ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY F.TOTAL_ORDER + COALESCE(SUM(J.TOTAL_ORDER), 0) DESC
LIMIT 3;