SELECT AP.APNT_NO, AP.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM (
    SELECT A.APNT_NO, P.PT_NO, P.PT_NAME, A.MCDP_CD, A.APNT_YMD, A.APNT_CNCL_YN, A.MDDR_ID
    FROM APPOINTMENT AS A JOIN PATIENT AS P ON A.PT_NO = P.PT_NO
    WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
        AND A.APNT_CNCL_YN = 'N'
        AND A.MCDP_CD = 'CS'
) AS AP JOIN DOCTOR AS D ON AP.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD