# 0부터 23까지 숫자 생성
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)

SELECT H.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOURS AS H LEFT JOIN ANIMAL_OUTS AS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR