WITH AVG_GRADE AS (
    SELECT EMP_NO, AVG(SCORE) AS NEW_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT E.EMP_NO,
    E.EMP_NAME,
    CASE WHEN G.NEW_SCORE >= 96 THEN 'S'
    WHEN G.NEW_SCORE >= 90 THEN 'A'
    WHEN G.NEW_SCORE >= 80 THEN 'B'
    ELSE 'C' END AS GRADE,
    CASE WHEN G.NEW_SCORE >= 96 THEN E.SAL * 0.2
    WHEN G.NEW_SCORE >= 90 THEN E.SAL * 0.15
    WHEN G.NEW_SCORE >= 80 THEN E.SAL * 0.1
    ELSE E.SAL * 0 END AS BONUS
FROM HR_EMPLOYEES AS E JOIN AVG_GRADE AS G ON E.EMP_NO = G.EMP_NO
ORDER BY EMP_NO