# P0014	맛있는마조유	CD_OL00004	식용유	8950
# P0051	맛있는배추김치	CD_KC00001	김치	19000
# P0074	맛있는김치찌개	CD_SU00004	국	2900
# P0093	맛있는허니버터칩	CD_CK00003	과자	1950

SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS FP_1
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') AND PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT AS FP_2
    WHERE CATEGORY = FP_1.CATEGORY
)
ORDER BY PRICE DESC;

# GPT 풀이
SELECT FP_1.CATEGORY, FP_1.PRICE, FP_1.PRODUCT_NAME
FROM FOOD_PRODUCT FP_1
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) FP_2
ON FP_1.CATEGORY = FP_2.CATEGORY AND FP_1.PRICE = FP_2.MAX_PRICE
ORDER BY FP_1.PRICE DESC;